/*
 * appconfig.h
 *
 *  Created on: Dec 1, 2015
 *      Author: MaartenWeyn
 */

#ifndef FRAMEWORK_HAL_CHIPS_SI4455_COMMON_INC_APPCONFIG_H_
#define FRAMEWORK_HAL_CHIPS_SI4455_COMMON_INC_APPCONFIG_H_


#define RADIO_CONFIG_DATA_RADIO_DELAY_AFTER_RESET_US (10000)

#define EZRADIO_PLUGIN_TRANSMIT
#define EZRADIO_PLUGIN_RECEIVE
#define EZRADIO_PLUGIN_CRC_ERROR
#define EZRADIO_DRIVER_EXTENDED_SUPPORT
//#define EZRADIO_PLUGIN_PTI


#endif /* FRAMEWORK_HAL_CHIPS_SI4455_COMMON_INC_APPCONFIG_H_ */
