# 
# OSS-7 - An opensource implementation of the DASH7 Alliance Protocol for ultra
# lowpower wireless sensor communication
#
# Copyright 2015 University of Antwerp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Add one or more CMAKE variables as '#define' statements to the "hal_defs.h"
# generated by the HAL_BUILD_SETTINGS_FILE MACRO. This MACRO adopts the same
# variable types used by the GEN_SETTINGS_HEADER MACRO. See the explanation of that macro
# in utils.cmake for more explanation.
#
# Usage:
#    HAL_HEADER_DEFINE([STRING <string_var> <string_var> ...] [ID <id_var> <id_var> ...] [BOOL <bool_var> <bool_var> ...] [NUMBER <number_var> <number_var> ...])
#
MACRO(HAL_HEADER_DEFINE)
    PARSE_HEADER_VARS("HAL_EXTRA_DEFS" ${ARGN})
ENDMACRO()

# Construct a "hal_defs.h" header file in the binary 'hal' directory containing 
# The various (cmake) settings for the framework. By default an 'empty' header file is generated.
# Settings can be added to this file by calling the HAL_HEADER_DEFINES macro.
#
# Usage:
#    HAL_BUILD_SETTINGS_FILE()
#
MACRO(HAL_BUILD_SETTINGS_FILE)
    GEN_SETTINGS_HEADER("${CMAKE_CURRENT_BINARY_DIR}/hal_defs.h" 
			STRING "${HAL_EXTRA_DEFS_STRING}" 
			BOOL "${HAL_EXTRA_DEFS_BOOL}" 
			ID "${HAL_EXTRA_DEFS_ID}"
			NUMBER "${HAL_EXTRA_DEFS_NUMBER}" 
			)			
    SET_GLOBAL(HAL_EXTRA_DEFS_STRING "")
    SET_GLOBAL(HAL_EXTRA_DEFS_BOOL "")
    SET_GLOBAL(HAL_EXTRA_DEFS_ID "")
    SET_GLOBAL(HAL_EXTRA_DEFS_NUMBER "")
ENDMACRO()
