var modules =
[
    [ "Hardware Abstraction Layer API", "group___h_a_l.html", "group___h_a_l" ],
    [ "Platform", "group__platform.html", null ],
    [ "Framework API", "group__framework.html", "group__framework" ],
    [ "D7AP", "group___d7_a_p.html", "group___d7_a_p" ],
    [ "Cmt_driver", "group__cmt__driver.html", "group__cmt__driver" ],
    [ "Cop_driver", "group__cop__driver.html", "group__cop__driver" ],
    [ "Edma_request", "group__edma__request.html", "group__edma__request" ],
    [ "Flexio_spi_driver", "group__flexio__spi__driver.html", "group__flexio__spi__driver" ],
    [ "Gpio_driver", "group__gpio__driver.html", "group__gpio__driver" ],
    [ "I2c_master", "group__i2c__master.html", "group__i2c__master" ],
    [ "I2c_slave", "group__i2c__slave.html", "group__i2c__slave" ],
    [ "Lpsci_driver", "group__lpsci__driver.html", "group__lpsci__driver" ],
    [ "Lpuart_driver", "group__lpuart__driver.html", "group__lpuart__driver" ],
    [ "Ltc_driver", "group__ltc__driver.html", "group__ltc__driver" ],
    [ "Ltc_driver_aes", "group__ltc__driver__aes.html", "group__ltc__driver__aes" ],
    [ "Ltc_driver_hash", "group__ltc__driver__hash.html", "group__ltc__driver__hash" ],
    [ "MMAU Driver", "group__mmau__driver.html", "group__mmau__driver" ],
    [ "Pit_driver", "group__pit__driver.html", "group__pit__driver" ],
    [ "Sdhc_std_def", "group__sdhc__std__def.html", "group__sdhc__std__def" ],
    [ "Sdramc_driver", "group__sdramc__driver.html", "group__sdramc__driver" ],
    [ "Slcd_driver", "group__slcd__driver.html", "group__slcd__driver" ],
    [ "Smartcard_driver", "group__smartcard__driver.html", "group__smartcard__driver" ],
    [ "Uart_driver", "group__uart__driver.html", "group__uart__driver" ],
    [ "Dspi_irq", "group__dspi__irq.html", "group__dspi__irq" ],
    [ "C90tfs_flash_driver", "group__c90tfs__flash__driver.html", "group__c90tfs__flash__driver" ],
    [ "Irtc_driver", "group__irtc__driver.html", "group__irtc__driver" ],
    [ "MMCAU Peripheral Driver", "group__mmcau.html", "group__mmcau" ],
    [ "Pit_irq", "group__pit__irq.html", null ],
    [ "Rtc_driver", "group__rtc__driver.html", "group__rtc__driver" ],
    [ "Htwint", "group__htwint.html", "group__htwint" ],
    [ "Spi_irq", "group__spi__irq.html", "group__spi__irq" ],
    [ "Cmt_hal", "group__cmt__hal.html", "group__cmt__hal" ],
    [ "Cop_hal", "group__cop__hal.html", "group__cop__hal" ],
    [ "Emvsim_hal", "group__emvsim__hal.html", "group__emvsim__hal" ],
    [ "Flexio_spi_hal", "group__flexio__spi__hal.html", "group__flexio__spi__hal" ],
    [ "Gpio_hal", "group__gpio__hal.html", "group__gpio__hal" ],
    [ "I2c_hal", "group__i2c__hal.html", "group__i2c__hal" ],
    [ "Lpsci_hal", "group__lpsci__hal.html", "group__lpsci__hal" ],
    [ "Lpuart_hal", "group__lpuart__hal.html", "group__lpuart__hal" ],
    [ "MMAU Hardware Abstraction Layer", "group__mmau__hal.html", "group__mmau__hal" ],
    [ "Fractional Data Types", "group__basic__data__types.html", "group__basic__data__types" ],
    [ "MMAU Mathematical Operations", "group__mmau__instructions.html", "group__mmau__instructions" ],
    [ "Pit_hal", "group__pit__hal.html", "group__pit__hal" ],
    [ "Port_hal", "group__port__hal.html", "group__port__hal" ],
    [ "Sim_hal", "group__sim__hal.html", "group__sim__hal" ],
    [ "Slcd_hal", "group__slcd__hal.html", "group__slcd__hal" ],
    [ "Uart_hal", "group__uart__hal.html", "group__uart__hal" ],
    [ "Sim_hal_k02f12810", "group__sim__hal__k02f12810.html", "group__sim__hal__k02f12810" ],
    [ "Sim_hal_k10d10", "group__sim__hal__k10d10.html", "group__sim__hal__k10d10" ],
    [ "Sim_hal_k11da50", "group__sim__hal__k11da50.html", "group__sim__hal__k11da50" ],
    [ "Sim_hal_k20d10", "group__sim__hal__k20d10.html", "group__sim__hal__k20d10" ],
    [ "Sim_hal_k21da5", "group__sim__hal__k21da5.html", "group__sim__hal__k21da5" ],
    [ "Sim_hal_k21fa12", "group__sim__hal__k21fa12.html", "group__sim__hal__k21fa12" ],
    [ "Sim_hal_k22f12810", "group__sim__hal__k22f12810.html", "group__sim__hal__k22f12810" ],
    [ "Sim_hal_k22f25612", "group__sim__hal__k22f25612.html", "group__sim__hal__k22f25612" ],
    [ "Sim_hal_k22f51212", "group__sim__hal__k22f51212.html", "group__sim__hal__k22f51212" ],
    [ "Sim_hal_k22fa12", "group__sim__hal__k22fa12.html", "group__sim__hal__k22fa12" ],
    [ "Sim_hal_k24f12", "group__sim__hal__k24f12.html", "group__sim__hal__k24f12" ],
    [ "Sim_hal_k24f25612", "group__sim__hal__k24f25612.html", "group__sim__hal__k24f25612" ],
    [ "Sim_hal_k26f18", "group__sim__hal__k26f18.html", "group__sim__hal__k26f18" ],
    [ "Sim_hal_k30d10", "group__sim__hal__k30d10.html", "group__sim__hal__k30d10" ],
    [ "Sim_hal_k40d10", "group__sim__hal__k40d10.html", "group__sim__hal__k40d10" ],
    [ "Sim_hal_k50d10", "group__sim__hal__k50d10.html", "group__sim__hal__k50d10" ],
    [ "Sim_hal_k51d10", "group__sim__hal__k51d10.html", "group__sim__hal__k51d10" ],
    [ "Sim_hal_k52d10", "group__sim__hal__k52d10.html", "group__sim__hal__k52d10" ],
    [ "Sim_hal_k53d10", "group__sim__hal__k53d10.html", "group__sim__hal__k53d10" ],
    [ "Sim_hal_k60d10", "group__sim__hal__k60d10.html", "group__sim__hal__k60d10" ],
    [ "Sim_hal_k63f12", "group__sim__hal__k63f12.html", "group__sim__hal__k63f12" ],
    [ "Sim_hal_k64f12", "group__sim__hal__k64f12.html", "group__sim__hal__k64f12" ],
    [ "Sim_hal_k65f18", "group__sim__hal__k65f18.html", "group__sim__hal__k65f18" ],
    [ "Sim_hal_k66f18", "group__sim__hal__k66f18.html", "group__sim__hal__k66f18" ],
    [ "Sim_hal_k80f25615", "group__sim__hal__k80f25615.html", "group__sim__hal__k80f25615" ],
    [ "Sim_hal_kl02z4", "group__sim__hal__kl02z4.html", "group__sim__hal__kl02z4" ],
    [ "Sim_hal_kl03z4", "group__sim__hal__kl03z4.html", "group__sim__hal__kl03z4" ],
    [ "Sim_hal_kl13z644", "group__sim__hal__kl13z644.html", "group__sim__hal__kl13z644" ],
    [ "Sim_hal_kl16z4", "group__sim__hal__kl16z4.html", "group__sim__hal__kl16z4" ],
    [ "Sim_hal_kl17z4", "group__sim__hal__kl17z4.html", "group__sim__hal__kl17z4" ],
    [ "Sim_hal_kl17z644", "group__sim__hal__kl17z644.html", "group__sim__hal__kl17z644" ],
    [ "Sim_hal_kl26z4", "group__sim__hal__kl26z4.html", "group__sim__hal__kl26z4" ],
    [ "Sim_hal_kl27z4", "group__sim__hal__kl27z4.html", "group__sim__hal__kl27z4" ],
    [ "Sim_hal_kl27z644", "group__sim__hal__kl27z644.html", "group__sim__hal__kl27z644" ],
    [ "Sim_hal_kl33z4", "group__sim__hal__kl33z4.html", "group__sim__hal__kl33z4" ],
    [ "Sim_hal_kl33z644", "group__sim__hal__kl33z644.html", "group__sim__hal__kl33z644" ],
    [ "Sim_hal_kl34z4", "group__sim__hal__kl34z4.html", "group__sim__hal__kl34z4" ],
    [ "Sim_hal_kl36z4", "group__sim__hal__kl36z4.html", "group__sim__hal__kl36z4" ],
    [ "Sim_hal_kl43z4", "group__sim__hal__kl43z4.html", "group__sim__hal__kl43z4" ],
    [ "Sim_hal_kl46z4", "group__sim__hal__kl46z4.html", "group__sim__hal__kl46z4" ],
    [ "Sim_hal_km34z7", "group__sim__hal__km34z7.html", "group__sim__hal__km34z7" ],
    [ "Sim_hal_kv10z1287", "group__sim__hal__kv10z1287.html", "group__sim__hal__kv10z1287" ],
    [ "Sim_hal_kv10z7", "group__sim__hal__kv10z7.html", "group__sim__hal__kv10z7" ],
    [ "Sim_hal_kv11z7", "group__sim__hal__kv11z7.html", "group__sim__hal__kv11z7" ],
    [ "Sim_hal_kv30f12810", "group__sim__hal__kv30f12810.html", "group__sim__hal__kv30f12810" ],
    [ "Sim_hal_kv31f12810", "group__sim__hal__kv31f12810.html", "group__sim__hal__kv31f12810" ],
    [ "Sim_hal_kv31f25612", "group__sim__hal__kv31f25612.html", "group__sim__hal__kv31f25612" ],
    [ "Sim_hal_kv31f51212", "group__sim__hal__kv31f51212.html", "group__sim__hal__kv31f51212" ],
    [ "Sim_hal_kw01z4", "group__sim__hal__kw01z4.html", "group__sim__hal__kw01z4" ],
    [ "Sim_hal_kw20z4", "group__sim__hal__kw20z4.html", "group__sim__hal__kw20z4" ],
    [ "Sim_hal_kw21d5", "group__sim__hal__kw21d5.html", "group__sim__hal__kw21d5" ],
    [ "Sim_hal_kw22d5", "group__sim__hal__kw22d5.html", "group__sim__hal__kw22d5" ],
    [ "Sim_hal_kw24d5", "group__sim__hal__kw24d5.html", "group__sim__hal__kw24d5" ],
    [ "Sim_hal_kw30z4", "group__sim__hal__kw30z4.html", "group__sim__hal__kw30z4" ],
    [ "Sim_hal_kw40z4", "group__sim__hal__kw40z4.html", "group__sim__hal__kw40z4" ]
];