var modules =
[
    [ "EFM32HG_ACMP", "group___e_f_m32_h_g___a_c_m_p.html", "group___e_f_m32_h_g___a_c_m_p" ],
    [ "EFM32HG_ACMP_BitFields", "group___e_f_m32_h_g___a_c_m_p___bit_fields.html", "group___e_f_m32_h_g___a_c_m_p___bit_fields" ],
    [ "EFM32HG_ADC", "group___e_f_m32_h_g___a_d_c.html", "group___e_f_m32_h_g___a_d_c" ],
    [ "EFM32HG_ADC_BitFields", "group___e_f_m32_h_g___a_d_c___bit_fields.html", "group___e_f_m32_h_g___a_d_c___bit_fields" ],
    [ "EFM32HG_AES", "group___e_f_m32_h_g___a_e_s.html", "group___e_f_m32_h_g___a_e_s" ],
    [ "EFM32HG_AES_BitFields", "group___e_f_m32_h_g___a_e_s___bit_fields.html", "group___e_f_m32_h_g___a_e_s___bit_fields" ],
    [ "EFM32HG_AF_Pins", "group___e_f_m32_h_g___a_f___pins.html", "group___e_f_m32_h_g___a_f___pins" ],
    [ "EFM32HG_AF_Ports", "group___e_f_m32_h_g___a_f___ports.html", "group___e_f_m32_h_g___a_f___ports" ],
    [ "EFM32HG_CALIBRATE", "group___e_f_m32_h_g___c_a_l_i_b_r_a_t_e.html", "group___e_f_m32_h_g___c_a_l_i_b_r_a_t_e" ],
    [ "EFM32HG_CMU", "group___e_f_m32_h_g___c_m_u.html", "group___e_f_m32_h_g___c_m_u" ],
    [ "EFM32HG_CMU_BitFields", "group___e_f_m32_h_g___c_m_u___bit_fields.html", "group___e_f_m32_h_g___c_m_u___bit_fields" ],
    [ "EFM32HG_DEVINFO", "group___e_f_m32_h_g___d_e_v_i_n_f_o.html", "group___e_f_m32_h_g___d_e_v_i_n_f_o" ],
    [ "EFM32HG_DEVINFO_BitFields", "group___e_f_m32_h_g___d_e_v_i_n_f_o___bit_fields.html", "group___e_f_m32_h_g___d_e_v_i_n_f_o___bit_fields" ],
    [ "EFM32HG_DMA", "group___e_f_m32_h_g___d_m_a.html", "group___e_f_m32_h_g___d_m_a" ],
    [ "EFM32HG_DMA_BitFields", "group___e_f_m32_h_g___d_m_a___bit_fields.html", "group___e_f_m32_h_g___d_m_a___bit_fields" ],
    [ "EFM32HG_DMA_DESCRIPTOR", "group___e_f_m32_h_g___d_m_a___d_e_s_c_r_i_p_t_o_r.html", "group___e_f_m32_h_g___d_m_a___d_e_s_c_r_i_p_t_o_r" ],
    [ "EFM32HG_DMACTRL_BitFields", "group___e_f_m32_h_g___d_m_a_c_t_r_l___bit_fields.html", "group___e_f_m32_h_g___d_m_a_c_t_r_l___bit_fields" ],
    [ "EFM32HG_DMAREQ_BitFields", "group___e_f_m32_h_g___d_m_a_r_e_q___bit_fields.html", "group___e_f_m32_h_g___d_m_a_r_e_q___bit_fields" ],
    [ "EFM32HG_EMU", "group___e_f_m32_h_g___e_m_u.html", "group___e_f_m32_h_g___e_m_u" ],
    [ "EFM32HG_EMU_BitFields", "group___e_f_m32_h_g___e_m_u___bit_fields.html", "group___e_f_m32_h_g___e_m_u___bit_fields" ],
    [ "EFM32HG_GPIO", "group___e_f_m32_h_g___g_p_i_o.html", "group___e_f_m32_h_g___g_p_i_o" ],
    [ "EFM32HG_GPIO_BitFields", "group___e_f_m32_h_g___g_p_i_o___bit_fields.html", "group___e_f_m32_h_g___g_p_i_o___bit_fields" ],
    [ "EFM32HG_I2C", "group___e_f_m32_h_g___i2_c.html", "group___e_f_m32_h_g___i2_c" ],
    [ "EFM32HG_I2C_BitFields", "group___e_f_m32_h_g___i2_c___bit_fields.html", "group___e_f_m32_h_g___i2_c___bit_fields" ],
    [ "EFM32HG_IDAC", "group___e_f_m32_h_g___i_d_a_c.html", "group___e_f_m32_h_g___i_d_a_c" ],
    [ "EFM32HG_IDAC_BitFields", "group___e_f_m32_h_g___i_d_a_c___bit_fields.html", "group___e_f_m32_h_g___i_d_a_c___bit_fields" ],
    [ "EFM32HG_LEUART", "group___e_f_m32_h_g___l_e_u_a_r_t.html", "group___e_f_m32_h_g___l_e_u_a_r_t" ],
    [ "EFM32HG_LEUART_BitFields", "group___e_f_m32_h_g___l_e_u_a_r_t___bit_fields.html", "group___e_f_m32_h_g___l_e_u_a_r_t___bit_fields" ],
    [ "EFM32HG_MSC", "group___e_f_m32_h_g___m_s_c.html", "group___e_f_m32_h_g___m_s_c" ],
    [ "EFM32HG_MSC_BitFields", "group___e_f_m32_h_g___m_s_c___bit_fields.html", "group___e_f_m32_h_g___m_s_c___bit_fields" ],
    [ "EFM32HG_MTB", "group___e_f_m32_h_g___m_t_b.html", "group___e_f_m32_h_g___m_t_b" ],
    [ "EFM32HG_MTB_BitFields", "group___e_f_m32_h_g___m_t_b___bit_fields.html", "group___e_f_m32_h_g___m_t_b___bit_fields" ],
    [ "EFM32HG_PCNT", "group___e_f_m32_h_g___p_c_n_t.html", "group___e_f_m32_h_g___p_c_n_t" ],
    [ "EFM32HG_PCNT_BitFields", "group___e_f_m32_h_g___p_c_n_t___bit_fields.html", "group___e_f_m32_h_g___p_c_n_t___bit_fields" ],
    [ "EFM32HG_PRS", "group___e_f_m32_h_g___p_r_s.html", "group___e_f_m32_h_g___p_r_s" ],
    [ "EFM32HG_PRS_BitFields", "group___e_f_m32_h_g___p_r_s___bit_fields.html", "group___e_f_m32_h_g___p_r_s___bit_fields" ],
    [ "EFM32HG_RMU", "group___e_f_m32_h_g___r_m_u.html", "group___e_f_m32_h_g___r_m_u" ],
    [ "EFM32HG_RMU_BitFields", "group___e_f_m32_h_g___r_m_u___bit_fields.html", "group___e_f_m32_h_g___r_m_u___bit_fields" ],
    [ "EFM32HG_ROMTABLE", "group___e_f_m32_h_g___r_o_m_t_a_b_l_e.html", "group___e_f_m32_h_g___r_o_m_t_a_b_l_e" ],
    [ "EFM32HG_ROMTABLE_BitFields", "group___e_f_m32_h_g___r_o_m_t_a_b_l_e___bit_fields.html", "group___e_f_m32_h_g___r_o_m_t_a_b_l_e___bit_fields" ],
    [ "EFM32HG_RTC", "group___e_f_m32_h_g___r_t_c.html", "group___e_f_m32_h_g___r_t_c" ],
    [ "EFM32HG_RTC_BitFields", "group___e_f_m32_h_g___r_t_c___bit_fields.html", "group___e_f_m32_h_g___r_t_c___bit_fields" ],
    [ "EFM32HG_TIMER", "group___e_f_m32_h_g___t_i_m_e_r.html", "group___e_f_m32_h_g___t_i_m_e_r" ],
    [ "EFM32HG_TIMER_BitFields", "group___e_f_m32_h_g___t_i_m_e_r___bit_fields.html", "group___e_f_m32_h_g___t_i_m_e_r___bit_fields" ],
    [ "EFM32HG_USART", "group___e_f_m32_h_g___u_s_a_r_t.html", "group___e_f_m32_h_g___u_s_a_r_t" ],
    [ "EFM32HG_USART_BitFields", "group___e_f_m32_h_g___u_s_a_r_t___bit_fields.html", "group___e_f_m32_h_g___u_s_a_r_t___bit_fields" ],
    [ "EFM32HG_USB", "group___e_f_m32_h_g___u_s_b.html", "group___e_f_m32_h_g___u_s_b" ],
    [ "EFM32HG_USB_BitFields", "group___e_f_m32_h_g___u_s_b___bit_fields.html", "group___e_f_m32_h_g___u_s_b___bit_fields" ],
    [ "EFM32HG_VCMP", "group___e_f_m32_h_g___v_c_m_p.html", "group___e_f_m32_h_g___v_c_m_p" ],
    [ "EFM32HG_VCMP_BitFields", "group___e_f_m32_h_g___v_c_m_p___bit_fields.html", "group___e_f_m32_h_g___v_c_m_p___bit_fields" ],
    [ "EFM32HG_WDOG", "group___e_f_m32_h_g___w_d_o_g.html", "group___e_f_m32_h_g___w_d_o_g" ],
    [ "EFM32HG_WDOG_BitFields", "group___e_f_m32_h_g___w_d_o_g___bit_fields.html", "group___e_f_m32_h_g___w_d_o_g___bit_fields" ],
    [ "Basic Math Functions", "group__group_math.html", null ],
    [ "Fast Math Functions", "group__group_fast_math.html", "group__group_fast_math" ],
    [ "Complex Math Functions", "group__group_cmplx_math.html", null ],
    [ "Filtering Functions", "group__group_filters.html", null ],
    [ "Matrix Functions", "group__group_matrix.html", null ],
    [ "Transform Functions", "group__group_transforms.html", null ],
    [ "Controller Functions", "group__group_controller.html", "group__group_controller" ],
    [ "Statistics Functions", "group__group_stats.html", null ],
    [ "Support Functions", "group__group_support.html", null ],
    [ "Interpolation Functions", "group__group_interpolation.html", "group__group_interpolation" ],
    [ "Examples", "group__group_examples.html", null ],
    [ "CMSIS Global Defines", "group___c_m_s_i_s__glob__defs.html", null ],
    [ "Defines and Type Definitions", "group___c_m_s_i_s__core__register.html", "group___c_m_s_i_s__core__register" ],
    [ "Functions and Instructions Reference", "group___c_m_s_i_s___core___function_interface.html", "group___c_m_s_i_s___core___function_interface" ],
    [ "CMSIS SIMD Intrinsics", "group___c_m_s_i_s___s_i_m_d__intrinsics.html", null ],
    [ "CMSIS Core Instruction Interface", "group___c_m_s_i_s___core___instruction_interface.html", null ],
    [ "Hardware Abstraction Layer API", "group___h_a_l.html", "group___h_a_l" ],
    [ "Platform", "group__platform.html", null ],
    [ "Framework API", "group__framework.html", "group__framework" ],
    [ "D7AP", "group___d7_a_p.html", "group___d7_a_p" ],
    [ "Parts", "group___parts.html", "group___parts" ],
    [ "EFM32HG_PRS_Signals", "group___e_f_m32_h_g___p_r_s___signals.html", "group___e_f_m32_h_g___p_r_s___signals" ],
    [ "EM_Library", "group___e_m___library.html", "group___e_m___library" ],
    [ "API common for all kits", "group___b_s_p_c_o_m_m_o_n.html", "group___b_s_p_c_o_m_m_o_n" ],
    [ "API for STK's", "group___b_s_p___s_t_k.html", "group___b_s_p___s_t_k" ],
    [ "Drivers", "group___drivers.html", "group___drivers" ],
    [ "EM_Drivers", "group___e_m___drivers.html", "group___e_m___drivers" ]
];