################################################################################
# This confidential and proprietary software may be used only as authorized 
#                      by a licensing agreement from                           
#                               Cortus S.A.
#
#                     (C) Copyright 2013 Cortus S.A.
#                          ALL RIGHTS RESERVED
#
# The entire notice above must be reproduced on all authorized copies
# and any such reproduction must be pursuant to a licensing agreement 
# from Cortus S.A. (http://www.cortus.com)
#
# $CortusRelease$
# $FileName$
#
################################################################################

export CC=aps-gcc -mcpu=aps3r

all %:
	${MAKE} -f Make.libc $*
